name: Build
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.0.0

      - name: Setup Deno environment
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Build
        run: ./scripts/build.sh

      - name: Get short commit SHA
        uses: benjlevesque/short-sha@v1.2
        id: short-sha

      - name: Upload artifacts
        uses: actions/upload-artifact@v2.3.1
        with:
          name: myrodlbot.${{ steps.short-sha.outputs.sha }}.CI
          path: dist/